### ISSUE TITLE
Matomo tracking implementation

### ISSUE THREAD

**Issue by hildmi** [ntnu-ai-lab/ntnu_sleepy#99]
- [x] track time spent on modules 
- [x] track number of finished modules
- [x] try: track time spent on parts of modules
- [x] try: filter on groups of users for research
- [x] track app stop
